export enum ContestTypes {
  LOTOFACIL = 'LOTOFACIL',
  QUINA = 'QUINA',
  MEGASENA = 'MEGASENA',
  LOTOMANIA = 'LOTOMANIA',
  TIMEMANIA = 'TIMEMANIA',
  FEDERAL = 'FEDERAL',
  DIADESORTE = 'DIADESORTE',
  SUPERSETE = 'SUPERSETE',
  UNTYPE = 'NULL',
}
